runtime: python39
handlers:
- url: /
  static_dir: /
  http_headers:
   Access-Control-Allow-Origin: 'https://reviewsafastapi.et.r.appspot.com/'
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
